### ISSUE TITLE
Including pandas dataframe from dict

### ISSUE THREAD

**Issue by yweidmann** [GLAMOS/dataflow#11]
Providing labeled arrays as returns from data objects:
https://pandas.pydata.org/pandas-docs/stable/index.html
e.g.: pandas.DataFrame.from_dict

**Comment by yweidmann** [comment]
Adding a property (or method) like massBalancesTable to DataObjects.Glacier.Glacier proving the key values of the mass balance as table object.

Following attributes have to be added (based on VAW file):
date0; date_s;date1;winter balance; annual balance

**Comment by yweidmann** [comment]
Open question:
How to differentiate between data of FixDate and Observations? Currently the information about the mass-balance type is given in the last column of the returned DataFrame.

**Comment by jlandmann** [comment]
I think the idea with the enum object in the last column is cool! 

I just pulled the code and it runs nicely! Thank you very much!
Would you, however, agree to rename the `massbalanceTable`attribute to `massbalanceDataFrame`or so? This sounds more intuitive to me...

**Comment by jlandmann** [comment]
Ahh...and do you think it is possible to generate column names from somewhere? This would be easier to handle than 1,2,3,4...
