### ISSUE TITLE
Providing access to geometries through GeoPandas

### ISSUE THREAD

**Issue by yweidmann** [GLAMOS/dataflow#12]
Providing properties or methods to access the geomtries of glaciers by using the GeoPandas interface:
http://geopandas.org/data_structures.html#geodataframe

Or as alternative as Well-Known-Text (WKT). Has to be clarified by jlandmann.

First priority:
- Outlines of current inventory

Next steps:
- Catchment areas

**Comment by yweidmann** [comment]
Export of the geometries through PostGIS query statement:
- eg: select **ST_AsText(geom)** from inventory.inventories; gives a WKT representation of the geometry back (eg POLYGON((7.98483691595121 46.6881000997106,7.98624331352786 46.6880925599618,7.9863387986071 46.688092892256)))

The result will be provided by a getter-property.

Coordinate system: WGS84 (as default)

**Comment by jlandmann** [comment]
Looks good to me!
Maybe we could direct output a geopandas GeoDataFrame, using the following piece of code:

    from shapely.wkt import loads
    gdf = gpd.GeoDataFrame(geometry=[loads(glacier.latestInventoryGeometry)]) 

and ensure that it works also for multiple geometries. Do you think that makes sense?

**Comment by yweidmann** [comment]
Mh, I do not agree: The GLAMOS library should be kept as generic as possible. A WellKnownText interface provides a very generic access to the database. Otherwise we have to implement all possible libraries to work with geometries.
Would it be ok for you, keeping the mentioned code in your application?

**Comment by jlandmann** [comment]
Mhh...okay, I get your point! Okay, then let's leave it like this.
