### ISSUE TITLE
Unlock IPs other than strict ETH domain

### ISSUE THREAD

**Issue by jlandmann** [GLAMOS/dataflow#21]
For me, for example, IPs other than the strict ETH domain to use the DB should be unlocked. My model will run operationally on a server in the WSL domain in Birmensdorf, so it would be cool to be able to access the database also from there.
For other users, an access from anywhere would also be useful I guess - I think one barrier (the private config file) is anyway enough or (for my taste) even too much. But I guess we should discuss this in the group.
CC @hussm @farinotti

**Comment by yweidmann** [comment]
The ISG (Simon Alder) does not agree to open the database to all IP's worldwide. But what he is willing to do, is adding some additional IP ranges as exceptions. 

I already invited the glaciologists of UniZH and UniFR to provide their IP-range. But not received yet.

Including the IP range of WSL Birmensdorf should be no problem at all. Just provide the IP-range of the subnet you are using.

**Comment by yweidmann** [comment]
Did it work with the WSL IP address?

**Comment by jlandmann** [comment]
Yes, just tried it from WSL VPN! Thanks, I will close the issue!
