### ISSUE TITLE
Including additional methods to retrieve glaciers from the database

### ISSUE THREAD

**Issue by yweidmann** [GLAMOS/dataflow#24]
Additional methods to be implemented to retrieve Glacier objects from DataReaders.DatabaseReaders.GlacierReader.

Currently only getAllGlaciers() and getGlacierBySgi(pkSgi) are implemented. It would be helpful to have functions to retrieve Glacier objects by the geographical location. Possible methods:

- getClosestGlacier(latitude, longitude): Getting the closest Glacier to the given location.
- getGlacierByBox(upperLeftLatitude, upperLeftLongitude, lowerRightLatitude, lowerRightLongitude): Getting all Glaciers within the given box.
- ?

What kind of other functions do we need?

**Comment by jlandmann** [comment]
Really cool idea!
I think getting a subset of glacier by polygon would be cool to have, this would be especially useful to those that work with hydrological catchments or region-/canton-based analyses.

**Comment by yweidmann** [comment]
Oups. I overlooked the mention idea "glacier by polygon". Will see about an implementation with a polygon as WKT as parameter. Should be easy.

Regarding hydrology and administrative boundaries: I prefer an implementation without geometries. Retrieving glaciers based on such properties can be done using the attributes ans logical operations.

For the major river catchment super easy to implement would be:

- Rhein
- Rhone
- Aare
- Limmat
- Reuss
- Ticino
- Inn and Adda

**Comment by jlandmann** [comment]
This is really really a cool feature! It makes it possible not only to make region-based requests, but also catchment-based requests (given a catchment polygon, which is quite easy to generate)! Great work!
