### ISSUE TITLE
Add Readme/License

### ISSUE THREAD

**Issue by jlandmann** [GLAMOS/dataflow#4]
More a formal thing, but I think we should have it as soon as this gets more public.

**Comment by yweidmann** [comment]
Fully agree. Do you have an example?

**Comment by jlandmann** [comment]
I think one of the two [MIT](https://choosealicense.com/licenses/mit/) or [Apache 2.0](https://choosealicense.com/licenses/apache-2.0/) could be fine, as the code is anyway just an application tailored to the GLAMOS DB. You can check them and tell me what you think.

There is also [choosealicense.com](https://choosealicense.com).

In terms of README, we could talk about the content on Friday and then I could make a PR.

**Comment by yweidmann** [comment]
Agreed on MIT licence. To be implemented:
https://choosealicense.com/licenses/mit/

**Comment by jlandmann** [comment]
Closed by #16.
