### ISSUE TITLE
Add private cfg to .gitignore?

### ISSUE THREAD

**Issue by jlandmann** [GLAMOS/dataflow#6]
Is this intentionally online?

**Comment by jlandmann** [comment]
Ah, I think it's a typo in the .gitignore (the "private" comes first)

**Comment by yweidmann** [comment]
That was accidentally. Mh, we have to think about a different method to keep the access to the database private.
The .gitignore contains now both versions (*.private.cfg and *.cfg.private). But in my case, git is not taking care about the ignore. I have to investigate.
