### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by jlandmann** [GLAMOS/dataflow#8]
As anyway the test directories are still empty, maybe they could be shifted to a common "tests". This would maybe save some extra folders.

I think the way it is commonly done for Python is like [here](https://github.com/kennethreitz/samplemod).

**Comment by yweidmann** [comment]
The *Tests-directories are pre-defined directories for UnitTests of the different packages (e.g. the package DataReaders has its UnitTests and test data in the package DataReadersTest). It simplifies the organisation of the operational- and test-code.

Unfortunately, to economize time I started without writing UnitTests for the different packages. But is was a mistake ...
